@startuml Blackjack
class Game {
  object $deck
  object $ManualPlayer
  object $dealer
  arrayobject $AutoPlayer
  int $PlayersNumber
  __construct($PlayersNumber)
  start()
  optionY()
  optionN()
  judge()
}
class Message {

}
class Deck {
  array $Deck
  InitDeck()
  DrawCard()
  GetDeck()

}
class Card {
  const SUITS
  const CARD_SCORE
  NewDeck()
}
class Player {
  string $name
  array $playerHand
  int $playerScore
  FirstDrawCards(Deck $deck)
  DrawCard(Deck $deck)
  GetScore()
  GetHand()

}
class ManualPlayer {
  string $name
  __construct($name)
  GetName()

}
class AutoPlayer {
  array $AutoPlayerName
  string $name
  __construct()
  GetName()

}
class Dealer {
}
@enduml
