@startuml Blackjack
rectangle BlackJack {
  usecase "Game Start" as UC1
  usecase "Draw Card" as UC2
  usecase "Judge" as UC3
  usecase "Game Finish" as UC4
}
actor "Player" as Me
actor "Dealer" as Dl
Dl --> UC2
UC1 --> UC2
UC2 --> UC3
UC3 --> UC4
Me --> UC2
@enduml
